# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:16
    container_name: notes-postgres
    env_file: ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/app/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes_user -d notes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio-notes
    ports:
      - "9000:9000"     # API (для приложений)
      - "9001:9001"     # Console (веб-интерфейс)
    environment:
      MINIO_ROOT_USER: admin12345
      MINIO_ROOT_PASSWORD: admin12345  # Замените на надежный пароль
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  backend:
    build: ./backend
    env_file: 
      - ./backend/.env 
    container_name: notes-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app  # для hot-reload в dev
volumes:
  pgdata:
  minio_data: